sudo: required
dist: trusty
env:
  global:
#  - TRAVIS_SECURE_ENV_VARS=true
  - VERSION="${TRAVIS_BRANCH}_`date +%Y%m%d`_${TRAVIS_BUILD_NUMBER}"
  - APPNAME=hello-world
services:
- docker
before_install:
- docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
- docker build -t ${DOCKER_USERNAME}/${APPNAME}:${VERSION} .
install:
- true
script:
- true
after_script:
- docker push airwavetechio/${APPNAME}:${VERSION}
- if [ "$TRAVIS_BRANCH" == "master" ]; then docker tag airwavetechio/${APPNAME}:${VERSION}
  airwavetechio/${APPNAME}:latest && docker push airwavetechio/${APPNAME}:latest; fi;
