sudo: required
dist: trusty
env:
  global:
#  - TRAVIS_SECURE_ENV_VARS=true
  - VERSION="${TRAVIS_BRANCH}_`date +%Y%m%d`_${TRAVIS_BUILD_NUMBER}"
  - APPNAME=hello-world
services:
- docker
before_install:
- docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
install:
- docker-compose up --build -d
script:
- curl http://localhost:4999
after_script:
- docker-compose down
- if [ "$TRAVIS_BRANCH" == "master" ]; then docker push airwavetechio/${APPNAME}:latest; fi;
- docker tag airwavetechio/${APPNAME}:latest airwavetechio/${APPNAME}:${VERSION} && docker push airwavetechio/${APPNAME}:${VERSION}
