apiVersion: apps/v1
kind: Deployment
metadata:
  name: airwavetechio-hello-world-deployment
  labels:
    app: airwavetech-helloworld
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airwavetech-helloworld
  template:
    metadata:
      labels:
        app: airwavetech-helloworld
    spec:
      containers:
      - name: hello-world
        image: airwavetechio/hello-world
        env:
        - name: "PORT"
          value: "4998"
        ports:
        - containerPort: 4998